import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useAppSelector } from "../public/redux/hooks";
import { darkTheme, lightTheme } from "../styles/theme";

const Home: NextPage = () => {
  const darkmode = useAppSelector((state) => state.darkmode);
  return (
    <>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
